### ISSUE TITLE
Add ability to set date format

### ISSUE THREAD

**Issue by chinghwayu** [deepjyoti30/simber#1]
# Feature Request

## Checklist

[x] I've searched the bugtracker for similar feature requests including closed ones.
[x] I will add the enhancement label to the issue.

## Description

In the formatter, we can use `{time}` but there's no way to set the date format as it's currently fixed to `%d/%m/%Y %H:%M:%S`. I'd like to set it to something else such as: `%Y-%m-%d %H:%M:%S`

**Comment by deepjyoti30** [comment]
@chinghwayu Thanks for opening the request. I had previously considered allowing that but never got around to it. I will take a look and see how that can be added!

**Comment by deepjyoti30** [comment]
@chinghwayu Should be added in the latest commit in the `unstable` branch. Consider testing it out!

**Comment by chinghwayu** [comment]
Thanks... seems ok with my test runs!

**Comment by deepjyoti30** [comment]
@chinghwayu Added in the latest release!
