### ISSUE TITLE
Method to destroy streams

### ISSUE THREAD

**Issue by chinghwayu** [deepjyoti30/simber#2]
# Feature Request

## Checklist

[x] I've searched the bugtracker for similar feature requests including closed ones.
[x] I will add the enhancement label to the issue.

## Description

The use case is for the execution of tests using pytest. For any particular session, there may be hundreds of tests. For each test, I'd like to generate a log file.

```
logger = Logger("mylogger", log_path="log1.txt", format="{message}")
logger.info("Just printing an info message from the test logger")
logger.update_disable_file(True)
logger = Logger("mylogger", log_path="log2.txt, format="{message}")
logger.info("Just printing another info message from the test logger")
```

I noticed that I need to disable the previous logger's file stream using `logger.update_disable_file(True)` or it will result in duplicated messages. However, if I do this 100 times for each session, I've noticed that there are 100 streams being kept in memory.

Can we have a method to destroy streams? Or is there another way to do this?

**Comment by deepjyoti30** [comment]
@chinghwayu As of now there is not method to do that. I think that's a necessary feature and I will add a dedicated method for that.

As for now, you can use the following workaround:

```python
from simber import Logger

logger = Logger("new-logger", log_path="test")
logger.info("Just a test")

# Now in order to remove the file stream.
file_stream = list(logger._streams)[0]

# Remove the stream from the set of streams and delete it after that
logger._streams.remove(file_stream)
del file_stream.stream

# Now add more streams to here accordingly.
```

Later on, I'll probably add a method that will accept an OutputStream instance and it will remove that from the logger.

**Comment by deepjyoti30** [comment]
@chinghwayu Also if you want to log to different files, you shouldn't create a new instance everytime? Just remove the old file stream instance and add a new file stream and log using the same logger.

**Comment by deepjyoti30** [comment]
@chinghwayu Please consider taking a look at 574e6784069d8b70d1f53bd29b3ea373bf113a22. I added a method named `remove_stream` that expects an `OutputStream` object.

Moreover, also added a `streams` property to get the list of `OutputStreams` connected to the logger.

You can clone the unstable repo and test out the changes, if you find any issues, you can comment here!

**Comment by deepjyoti30** [comment]
@chinghwayu Added a new release with the changes. You would be able to use that instead. Use the `remove_stream` method.

The equivalent to remove a stream from the above code would be something like this:

```python
from simber import Logger

logger = Logger("new-logger", log_path="test")
logger.info("Just a test")

file_stream = logger.streams[0]
logger.remove_stream(file_stream)

# Now add more streams to here accordingly.
```
