### ISSUE TITLE
Invalid Python release specifier

### ISSUE THREAD

**Issue by Technetium1** [deepjyoti30/simber#4]
# Bug report

## Checklist

[x] I have searched for similar bugs in the issues.
[x] I will add the bug label to this issue.

## Version Info

- Simber version: `0.2.5`
- 
## How Simber was installed?

It cannot be installed.

## Description

This is currently blocking the build for `ytmdl`: https://github.com/chaotic-aur/packages/issues/1595

Setup fails because there's an [invalid release specifier](https://peps.python.org/pep-0440/#compatible-release) here: 
https://github.com/deepjyoti30/simber/blob/b80cc11752818f0323b99f7111af67d62980500f/setup.py#L31

This results in the following error in [python-simber.log](https://builds.garudalinux.org/repos/chaotic-aur/logs/python-simber.log):
```
Warning: 'classifiers' should be a list, got type 'tuple'
error in simber setup command: 'python_requires' must be a string containing valid version specifiers; Invalid specifier: '>=3.*'
```

According to [Python packaging guidelines](https://packaging.python.org/en/latest/guides/distributing-packages-using-setuptools/#python-requires) the appropriate syntax is:
`python_requires=">=3",`

**Comment by deepjyoti30** [comment]
@Technetium1 Thanks for pointing out the issue. It is fixed in the latest release: `0.2.6`.
